# Generated by Django 4.1.5 on 2023-05-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
    ]
