# Generated by Django 4.1.5 on 2023-05-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutlog', '0002_remove_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(),
        ),
    ]
