# Generated by Django 4.1.5 on 2023-05-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutlog', '0004_remove_workout_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='best_set',
            new_name='best_weight',
        ),
    ]
